server:
  port: 8083

spring:
  application:
    name: service-consumer
  main:
    allow-bean-definition-overriding: true  # 允许Bean定义覆盖，解决冲突问题
  cloud:
    loadbalancer:
      ribbon:
        enabled: false  # 禁用 Ribbon，Spring Cloud LoadBalancer 替代它
      cache:
        enabled: false  # 禁用负载均衡缓存，避免空指针问题
    feign:
      circuitbreaker:
        enabled: true   # 启用Feign的断路器支持
      client:
        config:
          default:
            loggerLevel: FULL  # 配置Feign日志，便于查看请求
            # 添加错误解码器，避免空指针异常
            errorDecoder: feign.codec.ErrorDecoder.Default
            # 设置请求和响应的超时时间
            connectTimeout: 5000
            readTimeout: 5000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # 只连接到8761的注册中心
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: consumer-8083
    prefer-ip-address: true

# 服务提供者URL配置
provider:
  service:
    url: http://localhost:8081  # 直接指定服务提供者的URL，避免通过服务发现

resilience4j:
  circuitbreaker:
    instances:
      circuitBreakerA:  # 已有的断路器A，不要动
        failure-rate-threshold: 30
        sliding-window-type: TIME_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3

      circuitBreakerB:  # 现在新增断路器B
        failure-rate-threshold: 50       # 失败率超过50%熔断
        slow-call-rate-threshold: 30      # 慢调用比例达到30%熔断
        slow-call-duration-threshold: 2s  # 超过2秒的调用被认为是慢调用
        sliding-window-type: TIME_BASED   # 时间窗口
        sliding-window-size: 10           # 窗口长度10秒
        minimum-number-of-calls: 5         # 至少5个请求才开始计算
        wait-duration-in-open-state: 5s    # OPEN后等待5秒
        permitted-number-of-calls-in-half-open-state: 3 # HALF_OPEN时允许3个请求

# 限流器配置 - 独立配置部分
resilience4j.ratelimiter:
  instances:
    rateLimit2023:  # 使用全新名称避免与其他组件冲突
      limit-for-period: 5            # 每个周期内允许的最大请求数量为5
      limit-refresh-period: 2s       # 刷新周期为2秒
      timeout-duration: 500ms        # 等待获取权限的超时时间
      allow-health-indicator-to-fail: true
      register-health-indicator: true
      event-consumer-buffer-size: 100

# Actuator配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,ratelimiters
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true  # 启用断路器健康检查
    ratelimiters:
      enabled: true  # 启用限流器健康检查

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

# 隔离器配置
bulkhead:
  instances:
    providerServiceBulkhead:  # Provider服务的隔离器
      max-concurrent-calls: 10       # 允许并发执行的最大线程数为10
      max-wait-duration: 20ms       # 线程最大等待时间为20毫秒
      writable-stack-trace-enabled: true
